name: PR Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: PR Review
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            async function reviewPR() {
              const { data: changedFiles } = await github.rest.pulls.listFiles({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number,
              });

              const { data: pullRequest } = await github.rest.pulls.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number,
              });

              const commit_id = pullRequest.head.sha;

              for (const file of changedFiles) {
                if (!file.patch) continue;

                const lines = file.patch.split('\n');
                let lineNumber = 0;
                let position = 0;

                for (const line of lines) {
                  if (line.startsWith('@@')) {
                    const match = line.match(/@@ -\d+,?\d* \+(\d+),?\d* @@/);
                    if (match) {
                      lineNumber = parseInt(match[1]) - 1;
                      position = 0;
                    }
                    continue;
                  }

                  position++;

                  if (line.startsWith('+')) {
                    lineNumber++;
                    if (line.includes('TODO')) {
                      try {
                        await github.rest.pulls.createReviewComment({
                          owner: context.repo.owner,
                          repo: context.repo.repo,
                          pull_number: context.issue.number,
                          body: '변경된 라인에서 \'TODO\' 주석을 발견했습니다. 이 부분을 완료해주세요.',
                          path: file.filename,
                          commit_id: commit_id,
                          position: position
                        });
                        console.log(`Comment added to ${file.filename} at position ${position}`);
                      } catch (error) {
                        console.error(`Error adding comment: ${error.message}`);
                        console.error(`File: ${file.filename}, Position: ${position}`);
                      }
                    }
                  } else if (!line.startsWith('-')) {
                    lineNumber++;
                  }
                }
              }
            }

            await reviewPR();
